### ISSUE TITLE
referencesの訳語について

### ISSUE THREAD

**Issue by tai2** [ledsun/javascripting#9]
“In that file, define a variable named `numbers` that references this array” の訳を 「この配列を参照させます...」

にしているが、「参照させる」よりは、「代入する」のほうが自然?

**Comment by ledsun** [comment]
僕だったら、
「ファイルの中で、次の配列を表す変数 `numbers` を定義しましょう...」
と訳すと思います。

numbersでは、上のような感じで訳しました。
https://github.com/ledsun/javascripting/commit/9ef3af331a5b42f771fbada3189b9762f9a34488#diff-59e798b5b098c49da9eae0a951aaa643R13

プログラミングの課題としては「代入する」の方がわかりやすい気もします。
ただ、

1. 宣言と代入を2文に分けて書く気がします
1. 「表す」と「references」はそんなに遠くない気がします

ので「表す」にしました。

**Comment by tai2** [comment]
なるほど。似たような文例がすでにあったのですね。統一性持たせるためにそちらに合わせます。
